version: 0.0
os: linux

files:
  - source: build/libs
    destination: /home/ubuntu/app
    file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
